"""add_device_token

Revision ID: 0eb0027c4bb2
Revises: 33c83f0d6138
Create Date: 2026-05-30 15:08:04.041407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb0027c4bb2'
down_revision: Union[str, None] = '33c83f0d6138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('device_token', sa.String(length=255), nullable=True))
    op.alter_column('user_settings', 'weather_on_timeline',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_settings', 'weather_on_timeline',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('user_settings', 'device_token')
    # ### end Alembic commands ###
